version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login --username=sanketkalode --password=$PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t sanketkalode/awsflask .
      - docker tag sanketkalode/awsflask sanketkalode/awsflask:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push sanketkalode/awsflask:$IMAGE_TAG